language: objective-c
osx_image: xcode7.3
rvm: system
install:
  - sudo gem update --system
  - export GEM_HOME=tmp/ruby/2.0.0/
  - export PATH=${GEM_HOME}/bin:${PATH}
  - gem install bundler --no-document
  - bundle install --system
script:
  - bundle exec rake
  - soloist
